### ISSUE TITLE
Missing from Jcenter

### ISSUE THREAD

**Issue by erturne** [nebula-plugins/gradle-webpack-plugin#1]
README.md indicates that the plugin should be available from jcenter, but https://jcenter.bintray.com/com/netflix/nebula/ doesn't have it.

**Comment by kastork** [comment]
I can't find it anywhere, including jcenter.

**Comment by gambtho** [comment]
I don't think it was ever completed/released.   I submitted a pull request with a working version -- could temporarily use that locally if you wanted

**Comment by zimy** [comment]
Will it be fixed?

**Comment by tkruse** [comment]
Same problem here

**Comment by jrgleason** [comment]
Bump, Guess I am not using this dependency

**Comment by gambtho** [comment]
@jrgleason is you wanted to us the functionality this plugin would provide, this works pretty well.

https://plugins.gradle.org/plugin/com.moowork.node

quick example

`plugins {
  id "com.moowork.node" version "0.13"
}

task webpack(type: NodeTask) {
  script = file('node_modules/webpack/bin/webpack')
}

task karma(type: NpmTask) {
    dependsOn 'npmInstall'
    args = ['test']
}

project.tasks.processResources.dependsOn('npmInstall')
project.tasks.processResources.dependsOn('webpack')
project.tasks.test.dependsOn('karma')
`

**Comment by rspieldenner** [comment]
We're marking this project for deletion. Let us know if anybody wants to take it over.
